wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.20
    cli_version: 0.15.3
    framework: huggingface
    huggingface_version: 4.52.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1750493844.903797
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      - 71
      3:
      - 13
      - 23
      4: 3.9.20
      5: 0.15.3
      6: 4.52.4
      8:
      - 5
